### ISSUE TITLE
3600000000 세종특별자치시가 누락되어있습니다.

### ISSUE THREAD

**Issue by Kwon770** [kr-juso/api#2]
[시군구] 단위의 3611000000 세종특별자치시는 있는데,
[도시] 단위의 3600000000 세종특별자치시가 누락되어있습니다.

공개하신 [행정동코드 tsv 파일](https://github.com/kr-juso/administrationCode/blob/main/administrationCode.tsv#L1254) 과는 다르게, api에 요청해보면 (3600000000, 세종특별자치시)가 없습니다.

![스크린샷 2022-07-14 22 44 50](https://user-images.githubusercontent.com/49567744/178999084-2afa8a62-ab54-4c17-80b4-e6fe2e76752b.jpg)

**Comment by YeongCheon** [comment]
현재 공개되어 있는 API의 데이터는 행정동 코드 tsv 파일과 싱크가 완벽하게 일치하지 않습니다.
조만간 업데이트 해놓겠습니다.

**Comment by Kwon770** [comment]
넵, 감사합니다~

**Comment by YeongCheon** [comment]
[7월 1일자 데이터](https://www.mois.go.kr/frt/bbs/type001/commonSelectBoardArticle.do?bbsId=BBSMSTR_000000000052&nttId=92810) 적용 완료됐습니다.
