### ISSUE TITLE
행정동코드 사용법에 대한 추가적인 설명이 도큐먼트에 추가되면 좋을 것 같습니다.

### ISSUE THREAD

**Issue by Kwon770** [kr-juso/api#3]
기존 도큐먼트의 예시와 설명만 보면, [도/시] 2자리, [시/군/구] 2자리, [읍/면/동/리/..] 나머지 자리로 이해할 여지가 있습니다. 포항시처럼 특별시가 아닌데도 북구, 남구가 있는 몇몇 특별한 시외에는 이렇게 이해하고 사용해도 문제가 없기때문에 더욱 오해할 여지가 큽니다.

'앞에서부터 [도/시] 2자리, [시/군/구] 3자리, [읍/면/동/리/..] 그 나머지' 와 같은 추가적인 설명이 juso.dev 도큐먼트에 들어갔으면 합니다.

**Comment by YeongCheon** [comment]
말씀해주신 내용 추가해서 문서에 반영하였습니다.
저도 오해하고 있던 내용인데 알려주셔서 감사합니다.
