### ISSUE TITLE
대한민국 법정동 코드 조회 API 사용 시 법정동코드가 아닌 행정동코드가 적용되는 경우가 있습니다

### ISSUE THREAD

**Issue by LazzRuneLune** [kr-juso/api#4]
대한민국 법정동 코드 조회 API 사용 시
 - 부천시의 경우 법정동코드가 아닌 행정동코드가 적용돼서 원미동이 표시되지 않습니다
 [참고링크] (https://grpc-proxy-server-mkvo6j4wsq-du.a.run.app/v1/regcodes?regcode_pattern=41190*&is_ignore_zero=true)

**Comment by YeongCheon** [comment]
죄송합니다.
데이터 업데이트를 하면서 행정동 코드를 사용했었네요.
[여기](https://www.code.go.kr/stdcode/regCodeL.do) 데이터 받아서 다시 적용했습니다,

**Comment by LazzRuneLune** [comment]
죄송하긴요, 제가 감사하지요.
덕분에 프로젝트 마다 매번 키 요청할 필요없이 편하게 사용하고 있습니다 :)
