### ISSUE TITLE
administrationCode 문의

### ISSUE THREAD

**Issue by naninyang** [kr-juso/api#5]
https://github.com/kr-juso/administrationCode 이 레파지토리에서 이슈 등록으로 문의를 남겼었는데요.
`administrationCode` 레파지토리의 `administrationCode`와 `api` 레파지토리에 있는 `administrationCode`가 서로 다른건가요? api 호출시에 예전 데이터로 가져오고 있어서 테스트 해보니 예전 데이터로 불러오는 게 맞더라구요.

`administrationCode` 레파지토리에서는 파일이 업데이트 된 게 확인이 되는데 `api` 레파지토리에 있는 administrationCode 파일은 변화가 없어서 그런가 싶어서 문의 남깁니다.

**Comment by YeongCheon** [comment]
안녕하세요.

API에서 제공하고 있는 데이터는 [이 곳](https://www.code.go.kr/stdcode/regCodeL.do)에서 제공하는 **법정동** 데이터를 기반으로 작동합니다.

[administrationCode](https://github.com/kr-juso/administrationCode) 저장소에 있는 데이터는 **행정동** 데이터로, API에서 제공하는 내용과는 관련이 없습니다.

위 내용과는 별개로 API에서 제공하는 데이터도 최신 버전으로 업데이트 해놓았습니다.

제보 감사합니다.
