### ISSUE TITLE
서울특별시 소속의 모든 구 반환 api 누락 제보합니다.

### ISSUE THREAD

**Issue by pwdks** [kr-juso/api#6]
https://grpc-proxy-server-mkvo6j4wsq-du.a.run.app/v1/regcodes?regcode_pattern=11*000000
해당 요청에서 리턴 받는 배열 중에 '서울특별시 강북구'가 누락 되었는지 보이질 않습니다.

그리고 올려주신 api 유용하고 간편하게 잘 쓰고 있습니다. 감사합니다

**Comment by YeongCheon** [comment]
안녕하세요. 강북구는 아래의 형태로 호출해야 불러올 수 있습니다.

```
https://grpc-proxy-server-mkvo6j4wsq-du.a.run.app/v1/regcodes?regcode_pattern=11*00000
```

가이드에 잘못 소개되어 있는데 고쳐놓도록 하겠습니다.
